#pragma once

#define IDI_APP_ICON 101
#define IDR_APP_MANIFEST 1

#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 10
#define APP_VERSION_PATCH 0
#define APP_VERSION_BUILD 20260917

#define APP_VERSION_STRINGIFY(x) #x
#define APP_VERSION_TOSTRING(x) APP_VERSION_STRINGIFY(x)

#define APP_VERSION_STR      APP_VERSION_TOSTRING(APP_VERSION_MAJOR) "." APP_VERSION_TOSTRING(APP_VERSION_MINOR) "." APP_VERSION_TOSTRING(APP_VERSION_PATCH)
#define APP_VERSION_FULL_STR APP_VERSION_STR "." APP_VERSION_TOSTRING(APP_VERSION_BUILD)
#define APP_VERSION_WSTR     L"Version: v" APP_VERSION_STR
